spring:
    datasource:
       url: jdbc:mysql://192.168.137.128:3306/auth?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
       username: root
       password: 123456
    redis:
       host: 192.168.137.128
       port: 6379
    cloud:
       consul:
          host: 192.168.137.128
          port: 8500
    kafka:
       producer:
          bootstrap-servers: 192.168.137.128:9092
       consumer:
          bootstrap-servers: 192.168.137.128:9092